# Já tem:
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ingressos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=usuario
spring.datasource.password=senha
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.url=jdbc:mysql://127.0.0.1:3306/ingressos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.flyway.user=usuario
spring.flyway.password=senha
spring.flyway.driver-class-name=com.mysql.cj.jdbc.Driver
spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=none

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.connection.url=jdbc:mysql://127.0.0.1:3306/ingressos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.jpa.properties.hibernate.connection.username=senha
spring.jpa.properties.hibernate.connection.password=senha
spring.jpa.properties.hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver